// <auto-generated />
using System;
using BisnesManager.Database.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BisnesManager.Database.Migrations
{
    [DbContext(typeof(BissnesExpertSystemDiploma7Context))]
    partial class BissnesExpertSystemDiploma7ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BisnesManager.Database.Models.BisnesTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignmentsContent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("DateCreate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<short>("IdStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("IdUser")
                        .HasColumnType("smallint");

                    b.Property<int?>("Indentation")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("BisnesTask_pkey");

                    b.HasIndex(new[] { "IdStatus" }, "IX_BisnesTask_IdStatus");

                    b.HasIndex(new[] { "IdUser" }, "IX_BisnesTask_IdUser");

                    b.ToTable("BisnesTask", (string)null);
                });

            modelBuilder.Entity("BisnesManager.Database.Models.HolidayPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateCreate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndWeekends")
                        .HasColumnType("date");

                    b.Property<short>("IdUser")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("StartWeekends")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("HolidayPlan_pkey");

                    b.HasIndex(new[] { "IdUser" }, "IX_HolidayPlan_IdUser");

                    b.ToTable("HolidayPlan", (string)null);
                });

            modelBuilder.Entity("BisnesManager.Database.Models.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateCreate")
                        .HasColumnType("date");

                    b.Property<int>("EffectivCommunication")
                        .HasColumnType("integer");

                    b.Property<int>("HardSkils")
                        .HasColumnType("integer");

                    b.Property<short>("IdUser")
                        .HasColumnType("smallint");

                    b.Property<int>("LevelResponibility")
                        .HasColumnType("integer");

                    b.Property<int>("QualityWork")
                        .HasColumnType("integer");

                    b.Property<int>("SoftSkils")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Statistic_pkey");

                    b.HasIndex(new[] { "IdUser" }, "IX_Statistic_IdUser");

                    b.ToTable("Statistic", (string)null);
                });

            modelBuilder.Entity("BisnesManager.Database.Models.Status", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("Statuses_pkey");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("BisnesManager.Database.Models.User", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("CheckPhrase")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly>("DateCreate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateOnly?>("EndWorkTime")
                        .HasColumnType("date");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<short>("IdRole")
                        .HasColumnType("smallint");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte[]>("PhotoImage")
                        .HasColumnType("bytea");

                    b.Property<DateOnly>("StartWorkTime")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("Users_pkey");

                    b.HasIndex(new[] { "IdRole" }, "IX_Users_IdRole");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BisnesManager.Database.Models.UserRole", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValueSql("nextval('\"UserRoles_Id_seq\"'::regclass)");

                    b.Property<DateOnly>("DateCreate")
                        .HasColumnType("date");

                    b.Property<bool>("IsEditWorkTimeTable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEditWorkersRoles")
                        .HasColumnType("boolean");

                    b.Property<string>("Post")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id")
                        .HasName("UserRoles_pkey");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("BisnesManager.Database.Models.BisnesTask", b =>
                {
                    b.HasOne("BisnesManager.Database.Models.Status", "IdStatusNavigation")
                        .WithMany("BisnesTasks")
                        .HasForeignKey("IdStatus")
                        .IsRequired()
                        .HasConstraintName("Tasks_IdStatus_fkey");

                    b.HasOne("BisnesManager.Database.Models.User", "IdUserNavigation")
                        .WithMany("BisnesTasks")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("Tasks_IdUser_fkey");

                    b.Navigation("IdStatusNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("BisnesManager.Database.Models.HolidayPlan", b =>
                {
                    b.HasOne("BisnesManager.Database.Models.User", "IdUserNavigation")
                        .WithMany("HolidayPlans")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("HolidayPlan_IdUser_fkey");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("BisnesManager.Database.Models.Statistic", b =>
                {
                    b.HasOne("BisnesManager.Database.Models.User", "IdUserNavigation")
                        .WithMany("Statistics")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("Statistic_IdUser_fkey");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("BisnesManager.Database.Models.User", b =>
                {
                    b.HasOne("BisnesManager.Database.Models.UserRole", "IdRoleNavigation")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("Users_IdRole_fkey");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("BisnesManager.Database.Models.Status", b =>
                {
                    b.Navigation("BisnesTasks");
                });

            modelBuilder.Entity("BisnesManager.Database.Models.User", b =>
                {
                    b.Navigation("BisnesTasks");

                    b.Navigation("HolidayPlans");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("BisnesManager.Database.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
